import { EditorState } from "./types";

export const INITIAL_STATE: EditorState = {
  flattenOnSave: false,
  showPageManager: false,
  status: "idle",
  file: null,
  fileBuffer: null,
  numPages: 0,
  currentPage: 0,
  scale: 1.0,
  tool: "cursor",
  annotations: [],
  pageRotations: {},
  deletedPages: new Set(),
  pageOrder: [],
  history: [{ annotations: [], deletedPages: [], pageRotations: {}, pageOrder: [] }],
  historyStep: 0,
  color: "#000000",
  font: "Helvetica",
  opacity: 1.0,
  fontSize: 16,
  brushSize: 3,
  selectedId: null,
  error: null,
  showSignatureModal: false,
  showMetadataModal: false,
  showPasswordModal: false,
  metadata: { title: "", author: "", keywords: "" },
  savedSignature: null,
  savedName: null,
  savedStamp: null,
  savedQr: null,
  pageSize: { width: 0, height: 0 },
  showWatermarkModal: false,
  watermarkText: "CONFIDENTIAL",
  watermarkRange: "",
  extractedBlocks: [],
  activePalette: [],
  activeBgPalette: [],
  editingId: null,
  showQrModal: false,
  showStampModal: false,
  qrText: "",
};